"""Create temperatures table

Revision ID: 827d84611f79
Revises: 5524baaa22c3
Create Date: 2025-10-01 11:48:53.496897

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "827d84611f79"
down_revision: Union[str, Sequence[str], None] = "5524baaa22c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "temperatures",
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("temperature_date", sa.Integer(), nullable=False),
        sa.Column("temperature_time", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.Integer(), nullable=False),
        sa.Column("created_time", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("temperatures")
    # ### end Alembic commands ###
