"""Migrate table to postgres

Revision ID: 549413f4c8ff
Revises:
Create Date: 2025-10-01 14:36:31.601868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "549413f4c8ff"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cities_name"), "cities", ["name"], unique=True)
    op.create_table(
        "temperatures",
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("temperature_date", sa.Integer(), nullable=False),
        sa.Column("temperature_time", sa.Integer(), nullable=False),
        sa.Column(
            "created_date",
            sa.Integer(),
            server_default=sa.text(
                "CAST(to_char(now(),'YYYYMMDD') AS INTEGER)"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_time",
            sa.Integer(),
            server_default=sa.text(
                "CAST(to_char(now(),'HH24MISS') AS INTEGER)"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("temperatures")
    op.drop_index(op.f("ix_cities_name"), table_name="cities")
    op.drop_table("cities")
    # ### end Alembic commands ###
